# This is an example .yaml of the required secrets. Uncomment and replace the VALUES with your appropriate base64 encoded string

# apiVersion: v1
# kind: Secret
# metadata:
#   name: db
# type: Opaque
# data:
#   connectionString: BASE_64_ENCODED_DB_CONNECTION_STRING
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: auth
# type: Opaque
# data:
#   access.privateKey: BASE_64_ENCODED_PEM
#   access.publicKey: BASE_64_ENCODED_PEM
#   refresh.privateKey: BASE_64_ENCODED_PEM
#   refresh.publicKey: BASE_64_ENCODED_PEM
#   sendGridApiKey: BASE_64_ENCODED_API_KEY
