# The specs for the api backend reverse proxy
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: z2p-api
  labels:
    app: z2p-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: z2p-api
        tier: backend
        role: api
    spec:
      restartPolicy: Always
      containers:
        - name: server-api
          # The image of the container on google cloud
          # Replace the image name with image you created from your API server
          image: gcr.io/zero-to-production/server-api
          imagePullPolicy: Always
          # Configure all the environment variables
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: api.port
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: db
                  key: connectionString
            - name: ISSUER
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: access.issuer
            - name: AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: auth.audience
            - name: AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: auth.server
            - name: ACCESS_TOKEN_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: access.privateKey
            - name: REFRESH_TOKEN_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: refresh.privateKey
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: sendGridApiKey
            - name: ACCESS_TOKEN_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: access.publicKey
            - name: REFRESH_TOKEN_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: auth
                  key: refresh.publicKey
          readinessProbe:
            # The URL and port must match the exposed port/url on the API container
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 60
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: z2p-api-service
  labels:
    app: z2p-api-service
spec:
  selector:
    app: z2p-api
  ports:
    - name: z2p-api-port
      port: 80
      targetPort: 3000
  type: NodePort
